# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_plus_scraper_app', '0004_googleplusarticlesubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleplusarticle',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='googleplusarticle',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
